version: "3.9"
services:
  product-service:
    container_name: product-service
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - message-app_backend
    ports:
      - '3333:3333'
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST}

networks:
  message-app_backend:
    external: true